"""Hermes config.yaml merge primitive for `myah install` (Slice 4 sub-phase 4c).

Library-only — no CLI command yet. Sub-phase 4f wires `myah install`
end-to-end. This module replaces phase 6 of the bash at
`platform-oss/scripts/setup-myah-oss.sh` (lines 517-567) — the PyYAML
merge that flips `gateway.platforms.myah.enabled = true` in
``~/.hermes/config.yaml``.

Without this flag the Hermes gateway loads the Myah plugin (per
`hermes plugins install`) but never instantiates its platform adapter,
so the OSS probe reports ``plugin_installed=false`` despite the plugin
being on disk. This is the single most non-obvious failure mode in
the OSS install chain — see the bash comment block at
setup-myah-oss.sh:503-515 for the upstream gateway/run.py reference.

Cold-start budget: PyYAML stays lazy-imported inside the function body
(~50-100ms of import cost we don't pay until someone runs `myah install`).
The structural sentinel test in test_config_merge.py enforces this.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from loguru import logger


# The minimal fresh-config template. Hand-written rather than
# emitted by yaml.safe_dump so the header comment survives — PyYAML
# strips comments on round-trip. Mirrors setup-myah-oss.sh:520-525.
_FRESH_CONFIG_TEMPLATE = '''\
# Auto-generated by `myah install` — safe to edit by hand.
gateway:
  platforms:
    myah:
      enabled: true
'''


def enable_myah_platform(config_path: Path) -> Literal['created', 'updated', 'already_set']:
    """Merge ``gateway.platforms.myah.enabled = true`` into Hermes config.yaml.

    Mirrors ``ensure_myah_platform_enabled_in_config`` at
    setup-myah-oss.sh:517-567.

    Returns:
      - ``'created'`` if ``config_path`` did not exist and a fresh
        minimal config was written.
      - ``'already_set'`` if the file existed and ``myah.enabled`` was
        already ``True`` (strict identity match — see notes).
      - ``'updated'`` otherwise (any merge that resulted in a write).

    Behavior:
      - Missing file → write the fresh template (header comment + the
        bare gateway/platforms/myah path) and return ``'created'``.
      - Existing file → PyYAML-parse it. Any non-mapping intermediate
        (top-level, ``gateway``, ``platforms``, ``myah``) is defensively
        replaced with an empty dict, with a loguru warning emitted for
        each replacement. Then ``myah.enabled`` is set to ``True`` and
        the file is rewritten via ``yaml.safe_dump(..., sort_keys=False)``
        so user-edited ordering is preserved as much as PyYAML allows.

    Notes:
      - "Already set" detection uses strict ``is True`` identity (mirroring
        the bash's ``myah.get('enabled') is True`` at line 559). YAML
        truthy non-True values (``enabled: 1``, ``enabled: yes`` if a
        custom YAML loader produced anything other than ``True``) get
        replaced with canonical Python ``True`` so the upstream gateway
        code can rely on identity comparison.
      - When we re-write an existing file with ``yaml.safe_dump``, any
        comments in the original are stripped — known PyYAML limitation.
        The bash original has the same behavior. The ``already_set``
        short-circuit avoids the rewrite entirely so user-authored
        comments survive untouched on idempotent re-runs.
      - PyYAML is imported INSIDE the function body to keep the cold-start
        budget intact. ``test_module_does_not_import_yaml_at_top_level``
        enforces this.
    """
    # Lazy import — see module docstring.
    import yaml

    if not config_path.exists():
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(_FRESH_CONFIG_TEMPLATE)
        logger.info(f'Hermes config: created at {config_path} with gateway.platforms.myah.enabled=true')
        return 'created'

    raw = config_path.read_text()
    cfg = yaml.safe_load(raw)

    if not isinstance(cfg, dict):
        if cfg is not None:
            # yaml.safe_load returning None == empty file; not really a
            # "type mismatch" worth warning about.
            logger.warning(
                f'Hermes config {config_path}: top-level is not a mapping ({type(cfg).__name__}); replacing it'
            )
        cfg = {}

    gateway = cfg.get('gateway')
    if not isinstance(gateway, dict):
        if gateway is not None:
            logger.warning(
                f'Hermes config {config_path}: `gateway` is not a mapping ({type(gateway).__name__}); replacing it'
            )
        gateway = {}
        cfg['gateway'] = gateway

    platforms = gateway.get('platforms')
    if not isinstance(platforms, dict):
        if platforms is not None:
            logger.warning(
                f'Hermes config {config_path}: `gateway.platforms` is not a mapping '
                f'({type(platforms).__name__}); replacing it'
            )
        platforms = {}
        gateway['platforms'] = platforms

    myah = platforms.get('myah')
    if not isinstance(myah, dict):
        if myah is not None:
            logger.warning(
                f'Hermes config {config_path}: `gateway.platforms.myah` is not a mapping '
                f'({type(myah).__name__}); replacing it'
            )
        myah = {}
        platforms['myah'] = myah

    # Strict identity match — see docstring.
    already = myah.get('enabled') is True
    if already:
        logger.info(f'Hermes config {config_path}: gateway.platforms.myah.enabled already True')
        return 'already_set'

    myah['enabled'] = True
    config_path.write_text(yaml.safe_dump(cfg, sort_keys=False))
    logger.info(f'Hermes config {config_path}: gateway.platforms.myah.enabled set to True')
    return 'updated'


__all__ = ['enable_myah_platform']
