"""Tests for `myah.lib.cli.config_merge` — Slice 4 sub-phase 4c.

Replaces phase 6 of `platform-oss/scripts/setup-myah-oss.sh` (lines
517-567): the PyYAML merge that flips
`gateway.platforms.myah.enabled = true` in ~/.hermes/config.yaml.

Without this flag the gateway loads the plugin but never instantiates
its platform adapter — the single most non-obvious failure mode in
the OSS install chain (bash:503-515).
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from myah.lib.cli.config_merge import enable_myah_platform

# `loguru_caplog` fixture lives in conftest.py — auto-discovered by pytest.


# ── happy paths: fresh file, idempotent re-run ────────────────────────


class TestCreatesFileWhenMissing:
    def test_creates_file_when_missing(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'config.yaml'

        result = enable_myah_platform(config_path)

        assert result == 'created'
        assert config_path.is_file()
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded == {'gateway': {'platforms': {'myah': {'enabled': True}}}}

    def test_creates_file_includes_header_comment(self, tmp_path: Path) -> None:
        """The fresh template prepends a header comment that yaml.safe_dump
        would otherwise strip. Verify via raw read."""
        config_path = tmp_path / 'config.yaml'

        enable_myah_platform(config_path)

        raw = config_path.read_text()
        assert raw.startswith('# Auto-generated by')

    def test_creates_parent_dirs_if_needed(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'deep' / 'nested' / 'config.yaml'

        result = enable_myah_platform(config_path)

        assert result == 'created'
        assert config_path.is_file()


class TestEmptyFileTreatedAsMissingStructure:
    def test_empty_file_yields_fresh_structure_returns_updated(self, tmp_path: Path) -> None:
        """File exists but is empty (yaml.safe_load returns None). The
        file already existed so we return 'updated', not 'created'."""
        config_path = tmp_path / 'config.yaml'
        config_path.write_text('')

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded == {'gateway': {'platforms': {'myah': {'enabled': True}}}}


# ── defensive type-mismatch replacements (with warnings) ──────────────


class TestTopLevelNotMappingReplacesAndWarns:
    def test_top_level_is_a_list_gets_replaced(
        self, tmp_path: Path, loguru_caplog: pytest.LogCaptureFixture
    ) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text('- one\n- two\n')

        with loguru_caplog.at_level('WARNING'):
            result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded == {'gateway': {'platforms': {'myah': {'enabled': True}}}}
        assert any('not a mapping' in record.message for record in loguru_caplog.records)


class TestGatewayNotMappingReplacesAndWarns:
    def test_gateway_is_an_int_gets_replaced(
        self, tmp_path: Path, loguru_caplog: pytest.LogCaptureFixture
    ) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text('gateway: 42\n')

        with loguru_caplog.at_level('WARNING'):
            result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['gateway']['platforms']['myah']['enabled'] is True
        assert any('not a mapping' in record.message for record in loguru_caplog.records)


class TestPlatformsNotMappingReplacesAndWarns:
    def test_platforms_is_a_string_gets_replaced(
        self, tmp_path: Path, loguru_caplog: pytest.LogCaptureFixture
    ) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text("gateway:\n  platforms: 'invalid'\n")

        with loguru_caplog.at_level('WARNING'):
            result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['gateway']['platforms']['myah']['enabled'] is True
        assert any('not a mapping' in record.message for record in loguru_caplog.records)


class TestMyahNotMappingReplacesAndWarns:
    def test_myah_is_a_bool_gets_replaced(
        self, tmp_path: Path, loguru_caplog: pytest.LogCaptureFixture
    ) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text('gateway:\n  platforms:\n    myah: false\n')

        with loguru_caplog.at_level('WARNING'):
            result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['gateway']['platforms']['myah']['enabled'] is True
        assert any('not a mapping' in record.message for record in loguru_caplog.records)


# ── idempotence ───────────────────────────────────────────────────────


class TestAlreadySetReturnsAlreadySet:
    def test_already_true_returns_already_set_and_does_not_modify_mtime(
        self, tmp_path: Path
    ) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            '# Hand-written user comment\n'
            'gateway:\n'
            '  platforms:\n'
            '    myah:\n'
            '      enabled: true\n'
        )
        original_mtime = config_path.stat().st_mtime_ns
        original_text = config_path.read_text()

        result = enable_myah_platform(config_path)

        assert result == 'already_set'
        # We optimize the already-set path to skip the rewrite entirely so
        # user-authored comments survive unchanged.
        assert config_path.stat().st_mtime_ns == original_mtime
        assert config_path.read_text() == original_text


class TestDisabledFlagFlippedToTrue:
    def test_enabled_false_gets_flipped(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'gateway:\n  platforms:\n    myah:\n      enabled: false\n'
        )

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['gateway']['platforms']['myah']['enabled'] is True


class TestTruthyNonTrueValueReplaced:
    def test_int_one_replaced_with_python_true(self, tmp_path: Path) -> None:
        """YAML's `enabled: 1` loads as int `1` — truthy but NOT `True`.
        We must replace it with canonical `True` so upstream gateway code
        can rely on identity comparison."""
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'gateway:\n  platforms:\n    myah:\n      enabled: 1\n'
        )

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['gateway']['platforms']['myah']['enabled'] is True


# ── preservation of unrelated content ─────────────────────────────────


class TestPreservesUnrelatedTopLevelKeys:
    def test_logging_and_sentry_blocks_survive(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'logging:\n'
            '  level: DEBUG\n'
            'sentry:\n'
            '  dsn: foo\n'
            'gateway:\n'
            '  platforms:\n'
            '    myah:\n'
            '      enabled: false\n'
        )

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        assert loaded['logging']['level'] == 'DEBUG'
        assert loaded['sentry']['dsn'] == 'foo'
        assert loaded['gateway']['platforms']['myah']['enabled'] is True


class TestPreservesOtherMyahKeys:
    def test_sibling_keys_under_myah_survive(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'gateway:\n'
            '  platforms:\n'
            '    myah:\n'
            '      enabled: false\n'
            '      other_key: hello\n'
            '      nested:\n'
            '        deep: value\n'
        )

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        myah_block = loaded['gateway']['platforms']['myah']
        assert myah_block['enabled'] is True
        assert myah_block['other_key'] == 'hello'
        assert myah_block['nested']['deep'] == 'value'


class TestPreservesOtherPlatformsWhenPresent:
    def test_sibling_platform_blocks_survive(self, tmp_path: Path) -> None:
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'gateway:\n'
            '  platforms:\n'
            '    other_platform:\n'
            '      enabled: false\n'
            '    myah:\n'
            '      enabled: false\n'
        )

        result = enable_myah_platform(config_path)

        assert result == 'updated'
        loaded = yaml.safe_load(config_path.read_text())
        platforms = loaded['gateway']['platforms']
        assert platforms['other_platform']['enabled'] is False
        assert platforms['myah']['enabled'] is True


# ── log hygiene ───────────────────────────────────────────────────────


class TestEmitsOnlyOneStatusLogInHappyPath:
    def test_clean_disabled_to_true_emits_no_warnings(
        self, tmp_path: Path, loguru_caplog: pytest.LogCaptureFixture
    ) -> None:
        """A well-formed config that just needs the boolean flipped
        should not produce any WARNING-level noise."""
        config_path = tmp_path / 'config.yaml'
        config_path.write_text(
            'gateway:\n  platforms:\n    myah:\n      enabled: false\n'
        )

        with loguru_caplog.at_level('WARNING'):
            result = enable_myah_platform(config_path)

        assert result == 'updated'
        warning_records = [r for r in loguru_caplog.records if r.levelname == 'WARNING']
        assert warning_records == []


# ── defense-in-depth sentinel: PyYAML must stay lazy-loaded ───────────


def test_module_does_not_import_yaml_at_top_level() -> None:
    """Sentinel: `yaml` must be lazy-imported inside `enable_myah_platform`.

    PyYAML is ~50-100ms of cold-start latency; if it leaks to module top
    every `myah` CLI invocation pays for it. This test mirrors
    `test_token_gen.test_module_imports_only_lightweight_stdlib`.
    """
    from myah.lib.cli import config_merge

    source = Path(config_merge.__file__).read_text(encoding='utf-8')
    head = source.split('\ndef ', 1)[0]
    # 'import yaml' or 'from yaml import …' at module top is the failure mode.
    assert 'import yaml' not in head, 'config_merge top-level imports yaml'
    assert 'from yaml' not in head, 'config_merge top-level imports from yaml'
