"""Contract completeness check — every Hermes-emitted symbol has a contract.

This is the single highest-value invariant in Workstream I (per the spec at
``docs/superpowers/specs/2026-04-24-workstream-i-platform-hermes-contract-design.md``
§4.1). It walks the upstream Hermes submodule source files looking for
literal event-name strings and aux-task allow-list entries, and asserts each
discovered string is present in the platform-side contract.

When this test goes red on a fresh Hermes submodule bump, the action is to
add the new event class (or aux task value) in
``platform/shared/contract/{events,enums}.py`` and the matching wire handler
in ``platform/backend/myah/utils/hermes_stream_handler.py``. CI red
catches the drift before it reaches production.

Discovery strategy: a conservative regex over every ``.py`` file under
``agent/hermes/gateway/`` looking for the wire literal
``"event": "X"`` or ``'event': 'X'``. The test is intentionally
over-eager — we'd rather fail on a string that turns out to be a comment
than miss a real event. Spurious matches are easy to suppress via the
``_IGNORE_EVENTS`` set if any ever appear.
"""
from __future__ import annotations

import json
import re
from collections.abc import Iterable
from pathlib import Path
from typing import get_args

import pytest

from shared.contract.events import HermesEvent

# ── Filesystem layout ──────────────────────────────────────────────────────
# Plan B PR B (2026-05-12) deleted the agent/hermes/ submodule. Tests now
# load the upstream contract data from a snapshot JSON committed to the
# repo. The snapshot is regenerated by
# platform-oss/shared/contract/_generate_snapshot.py whenever HERMES_SHA
# bumps — enforced by .github/workflows/refresh-contract-snapshot.yml.
_REPO_ROOT = Path(__file__).resolve().parents[4]
_SNAPSHOT_PATH = _REPO_ROOT / 'platform-oss' / 'shared' / 'contract' / 'upstream-snapshot.json'

# Plugin source for adapter walk (now at repo root after Plan B PR A).
_MYAH_PLUGIN_ROOT = _REPO_ROOT / 'myah-hermes-plugin' / 'myah_hermes_plugin'
_MYAH_PLUGIN_ADAPTER = _MYAH_PLUGIN_ROOT / 'myah_platform' / 'adapter.py'

# ── Discovery regex (still used for adapter walk in some tests) ────────────
_EVENT_LITERAL_RE = re.compile(
    r"""['"]event['"]\s*:\s*['"]([\w.]+)['"]""",
    re.MULTILINE,
)

# Spurious matches go here. None today — kept as a documented escape hatch
# for the future.
_IGNORE_EVENTS: frozenset[str] = frozenset()


def _load_snapshot() -> dict:
    """Load the upstream-snapshot.json committed at Plan B PR A/B time.

    The snapshot replaces the live submodule walk — see Plan B Spec §3.6
    Option α. Regenerated automatically on every HERMES_SHA bump via the
    refresh-contract-snapshot.yml CI workflow.
    """
    if not _SNAPSHOT_PATH.exists():
        pytest.skip(
            f'upstream-snapshot.json not found at {_SNAPSHOT_PATH}. '
            f'Generate via platform-oss/shared/contract/_generate_snapshot.py.',
        )
    return json.loads(_SNAPSHOT_PATH.read_text())


def _discover_hermes_event_types() -> set[str]:
    """Return every Hermes-emitted event name from the snapshot.

    Pre-Plan-B-PR-B this function walked agent/hermes/gateway/ at test time.
    Post-PR-B it loads the snapshot generated at HERMES_SHA bump time.
    """
    snapshot = _load_snapshot()
    discovered: set[str] = set(snapshot.get('hermes_event_types', []))
    # Walk the local plugin source for completeness — the plugin can ship
    # new event types between snapshot regenerations.
    if _MYAH_PLUGIN_ROOT.exists():
        for py_file in _MYAH_PLUGIN_ROOT.rglob('*.py'):
            try:
                text = py_file.read_text(encoding='utf-8')
            except (OSError, UnicodeDecodeError):
                continue
            for match in _EVENT_LITERAL_RE.finditer(text):
                discovered.add(match.group(1))
    return discovered - _IGNORE_EVENTS


def _contract_event_literals() -> set[str]:
    """Return the set of ``event`` literal values declared in the contract.

    Walks the discriminated union :data:`HermesEvent` and pulls each
    constituent class's ``event`` field literal value. The ``HermesEvent``
    type is ``Annotated[Union[...], Field(discriminator='event')]``, so
    ``get_args`` returns ``(Union[Class1, Class2, ...], Field(...))``.
    """
    annotated_args = get_args(HermesEvent)
    union_type = annotated_args[0]
    event_classes = get_args(union_type)
    literals: set[str] = set()
    for cls in event_classes:
        annotation = cls.model_fields['event'].annotation
        # ``annotation`` is ``Literal["message.delta"]``; ``get_args``
        # returns ``("message.delta",)``.
        for value in get_args(annotation):
            if isinstance(value, str):
                literals.add(value)
    return literals


# ── Tests ───────────────────────────────────────────────────────────────────


def test_every_hermes_event_is_in_the_contract() -> None:
    """Every event the Hermes gateway emits has a matching contract class.

    Failure here means the platform's stream handler will receive an event
    type the typed-validation gate at ``hermes_stream_handler.py:358``
    rejects with a warning — and the user-visible feature behind that
    event will silently degrade. Add the missing event class to
    ``shared/contract/events.py`` and a dispatch branch to the handler.
    """
    discovered = _discover_hermes_event_types()
    contract = _contract_event_literals()
    missing = discovered - contract
    assert not missing, (
        f'Hermes emits these event types not in the contract: {sorted(missing)}. '
        f'Add the new ``BaseModel`` subclass(es) to '
        f'``platform/shared/contract/events.py``, append to ``HermesEvent`` '
        f'union, then re-run ``bash platform/scripts/generate-ts-contract.sh``.'
    )


def test_contract_does_not_invent_events() -> None:
    """The contract may not declare event types Hermes never emits.

    A contract-only event would silently bake a non-existent string into
    the frontend's exhaustive switches and fail to catch the moment when
    the assumption changes.
    """
    discovered = _discover_hermes_event_types()
    contract = _contract_event_literals()
    invented = contract - discovered
    assert not invented, (
        f"Contract declares these event types Hermes doesn't emit: {sorted(invented)}. "
        f'Either the upstream emitter was removed (delete the contract entry) '
        f'or the discovery regex needs widening.'
    )


def test_at_least_one_hermes_event_was_discovered() -> None:
    """Sanity check: the discovery regex actually finds something.

    A silent regression in the regex (or an unexpected refactor of how
    Hermes emits events) would mask drift forever. Insist on a non-empty
    discovery set so any future refactor surfaces here.
    """
    discovered = _discover_hermes_event_types()
    assert len(discovered) >= 5, (
        f'Hermes event discovery regex found only {len(discovered)} events — '
        f'something is wrong with the regex or the submodule layout. '
        f'Discovered: {sorted(discovered)}'
    )


# ── Aux task coverage (Phase 3 cross-check, gracefully skipped if absent) ──
#
# Phase 3 of Workstream I introduces ``shared.contract.enums.AuxTask`` and
# ``AUX_ALLOWED_TASKS``. Phase 5 (this file) was authored before Phase 3
# landed, so the test below uses ``pytest.importorskip`` to handle the
# pre-Phase-3 state without failing CI.


_AUX_ALLOWED_RE = re.compile(
    r'_AUX_ALLOWED_TASKS\s*=\s*frozenset\s*\(\s*\{([^}]*)\}',
    re.MULTILINE | re.DOTALL,
)
_AUX_TASK_STRING_RE = re.compile(r"['\"]([a-z_]+)['\"]")


def _discover_hermes_aux_tasks() -> set[str]:
    """Return aux task names from snapshot + plugin adapter.

    Post-Plan-B-PR-B the snapshot is the upstream-pinned source of truth.
    The plugin adapter is still walked live since it ships with the Myah
    plugin and can grow new tasks between snapshot regenerations.
    """
    snapshot = _load_snapshot()
    discovered: set[str] = set(snapshot.get('hermes_aux_tasks', []))

    # Walk the local plugin adapter for any newly-added tasks.
    if _MYAH_PLUGIN_ADAPTER.exists():
        text = _MYAH_PLUGIN_ADAPTER.read_text(encoding='utf-8')
        match = _AUX_ALLOWED_RE.search(text)
        if match:
            discovered.update(_AUX_TASK_STRING_RE.findall(match.group(1)))

    return discovered


def test_every_hermes_aux_task_is_in_the_contract() -> None:
    """Every aux task Hermes accepts has an enum entry on the platform side.

    Skipped until Phase 3 ships ``AuxTask`` and ``AUX_ALLOWED_TASKS``; once
    they exist this test guarantees the cross-tier allow-list cannot drift.
    """
    enums_module = pytest.importorskip(
        'shared.contract.enums',
        reason='Phase 3 contract enums not yet present',
    )
    aux_task_enum = getattr(enums_module, 'AuxTask', None)
    if aux_task_enum is None:
        pytest.skip('Phase 3 AuxTask enum not yet present in shared.contract.enums')
    discovered = _discover_hermes_aux_tasks()
    contract = {member.value for member in aux_task_enum}
    missing = discovered - contract
    assert not missing, (
        f'Hermes allows these aux tasks not in the contract: {sorted(missing)}. '
        f'Add them to ``AuxTask`` in ``platform/shared/contract/enums.py``.'
    )
    invented = contract - discovered
    assert not invented, (
        f"Contract declares these aux tasks Hermes doesn't accept: {sorted(invented)}. "
        f'Remove them or update the upstream allow-list.'
    )


# ── Tooling: helper to debug locally ────────────────────────────────────────


def _summarise() -> dict[str, Iterable[str]]:
    """Convenience helper — invoked manually, not by pytest.

    Run with: ``cd platform && .venv/bin/python -c
    "from shared.contract.__tests__.test_contract_completeness import _summarise; print(_summarise())"``
    """
    return {
        'discovered_events': sorted(_discover_hermes_event_types()),
        'contract_events': sorted(_contract_event_literals()),
    }
